# Generated by Django 3.2 on 2021-04-17 17:49

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
