# Generated by Django 3.2 on 2021-04-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, default=None),
        ),
    ]
