# Generated by Django 3.2 on 2021-06-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_date2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date2',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
